datasets:
  path:
    test:
      input: '../resource/datasets/input'
      output: '../resource/datasets/output'
    train:
      input: '../resource/datasets/train/input'
      mask: '../resource/datasets/train/mask'